services:
  # Base de Datos
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend_intro_devops_casino/db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_admin -d my_database"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  # Backend (Node.js 20 Alpine)
  backend:
    build:
      context: ./backend_intro_devops_casino
      dockerfile: Dockerfile
    container_name: node_backend
    restart: always
    environment:
      DATABASE_URL: postgres://user_admin:secret_password@db:5432/my_database
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user_admin
      DB_PASSWORD: secret_password
      DB_NAME: my_database
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  # Frontend (Angular + Nginx Unprivileged)
  frontend:
    build:
      context: ./frontend_intro_devops_casino
      dockerfile: Dockerfile
    container_name: angular_frontend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  postgres_data: