server {
    listen 8080;
    server_name localhost;

    # Carpeta donde están los archivos estáticos del Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

# PROXY INVERSO: Aquí es donde se conecta con el Backend
    location /api/ {
        # Corregido: Protocolo simple, IP correcta y puerto 3000 completo
        proxy_pass http://107.20.65.120:3000/; 
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

}