server {
    listen 8080;
    server_name localhost;

    # Carpeta donde están los archivos estáticos del Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # PROXY INVERSO: Conexión unificada al Backend
    location /api/ {
        proxy_pass http://100.54.209.243:3000;
        
        # Protocolo y Sockets (Solo una vez)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Cabeceras de red esenciales
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Tiempos de espera optimizados para evitar el 502/504 en los juegos
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}