server {
    listen 8080;
    server_name localhost;

    # Carpeta donde están los archivos estáticos del Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # PROXY INVERSO: Aquí es donde se conecta con el Backend
    location /api/ {
        # IMPORTANTE: Reemplaza con la IP de tu instancia de Backend
        proxy_pass http://http://107.20.65.120:30;