apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: casino
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 851725353324.dkr.ecr.us-east-1.amazonaws.com/casino/frontend:latest
          ports:
            - containerPort: 8080
